import type {
  ProviderInstance,
  SettingsState,
} from './types/settings.js';

export const DEFAULT_PROVIDERS: ProviderInstance[] = [
  {
    instanceId: 'openai-gpt5',
    enabled: true,
    displayName: 'OpenAI GPT-5.5',
    kind: 'openai',
    baseUrl: 'https://api.openai.com/v1',
    defaultModel: 'gpt-5.5',
    chatModel: 'gpt-5.5',
    diagnosisModel: 'gpt-5.5',
    summaryModel: 'gpt-5.5',
    advanced: { timeout: 30, retries: 3, streaming: true, temperature: 0.7, maxTokens: 4096, reasoningEffort: 'auto', proxy: '' },
  },
  {
    instanceId: 'anthropic-claude4',
    enabled: true,
    displayName: 'Anthropic Claude',
    kind: 'anthropic',
    baseUrl: 'https://api.anthropic.com/v1',
    defaultModel: 'claude-opus-4-8',
    chatModel: 'claude-opus-4-8',
    diagnosisModel: 'claude-opus-4-8',
    summaryModel: 'claude-sonnet-4-6',
    advanced: { timeout: 60, retries: 2, streaming: true, temperature: 0.5, maxTokens: 8192, reasoningEffort: 'high', proxy: '' },
  },
  {
    instanceId: 'deepseek-v4',
    enabled: false,
    displayName: 'DeepSeek V4',
    kind: 'deepseek',
    baseUrl: 'https://api.deepseek.com/v1',
    defaultModel: 'deepseek-v4-pro',
    chatModel: 'deepseek-v4-flash',
    diagnosisModel: 'deepseek-v4-pro',
    summaryModel: 'deepseek-v4-flash',
    advanced: { timeout: 45, retries: 3, streaming: true, temperature: 0.6, maxTokens: 4096, reasoningEffort: 'auto', proxy: '' },
  },
  {
    instanceId: 'google-gemini3',
    enabled: false,
    displayName: 'Google Gemini 3.5',
    kind: 'gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    defaultModel: 'gemini-3.5-flash',
    chatModel: 'gemini-3.5-flash',
    diagnosisModel: 'gemini-3.5-flash',
    summaryModel: 'gemini-3.5-flash',
    advanced: { timeout: 30, retries: 2, streaming: true, temperature: 0.5, maxTokens: 8192, reasoningEffort: 'auto', proxy: '' },
  },
];

export function createDefaultSettings(): SettingsState {
  return {
    general: { startupBehavior: 'restore-last', checkForUpdates: true, crashReports: true },
    modelProviders: { providers: DEFAULT_PROVIDERS.map(p => ({ ...p, advanced: { ...p.advanced } })) },
    assistant: {
      name: 'Default Assistant',
      defaultWorkMode: 'diagnosis-suggestions',
      responseStyle: 'detailed',
      evidenceRequirement: 'standard',
      autoScanScope: 'current-asset',
      lowEvidenceBehavior: 'ask-user',
      repairBehaviors: {
        autoCollectEvidence: true,
        autoRetryOnFailure: false,
        suggestAlternatives: true,
        requireApproval: true,
        notifyOnComplete: true,
        logVerbose: false,
      },
    },
    appearance: {
      theme: 'ue-agent',
      accentColor: 'blue',
      density: 'comfortable',
      fontSize: 'medium',
      layouts: { showLeftRail: true, showProjectExplorer: true, showRightInspector: true, showStatusBar: false },
      chatDisplay: { showTimestamps: true, showAvatars: true, codeSyntaxHighlight: true, collapseLongMessages: false, showActionButtons: true },
    },
    language: { uiLanguage: 'zh-CN', assistantReplyLanguage: 'follow-ui', terminologyDisplay: 'english', timeFormat: '24h' },
    ueConnection: { projectPath: '', enginePath: '', host: 'localhost', port: 28470, scanOnStartup: true, watchAssetChanges: true, autoScan: false, taskRelatedOnly: true },
    sandboxSecurity: {
      defaultModificationMode: 'sandbox-always',
      writeBackConfirmations: { sandboxApply: true, promote: true, rollback: true, bulkOperation: true },
      sandboxLocation: '/Game/Scratch/',
      rollbackStrategy: 'automatic-snapshot',
      riskPolicy: 'cautious',
      protectedContent: { blueprints: true, behaviorTrees: true, blackboards: true, assets: false, projectSettings: true },
      protectedPaths: ['/Game/Scratch/', '/Game/Test/'],
    },
    privacyLog: {
      dataUsage: { anonymousTelemetry: false, crashReports: true, usageStatistics: false, improvementProgram: false },
      logging: { bridgeCommunication: true, agentStateChanges: true, userActions: false, performanceMetrics: false },
      sensitiveInfoProtection: { maskApiKeys: true, maskFilePaths: true, maskAssetNames: false, maskUserInput: false },
      logRetention: '30d',
    },
    advanced: {
      developerMode: false,
      devToggles: { showRawBridgePayload: false, enableVerboseLogging: false, showMockScenarioControls: false, enableDevTools: false, bypassSandboxPromote: false, showExperimentalUi: false },
      agentExecutionLimits: { maxRetries: 3, maxCompileRetries: 5, maxProposalCandidates: 3, sessionTimeoutMinutes: 30 },
      experimentalFeatures: { enableAutoScan: false, enableMultiStepRepair: false, enableAutoRollback: false },
    },
  };
}
